# Generated by Django 5.1.15 on 2026-07-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ('document_id', 'chunk_index'),
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='chunks_docu_documen_792325_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index')],
            },
        ),
    ]
